### ISSUE TITLE
Cannot detect non-exist email address

### ISSUE THREAD

**Issue by ixehad** [cuchakma/Email-Record#2]
If someone uses a nonexistent email address it says 'sent successfully'. If it could detect it may a new feature.

https://prnt.sc/12y976d

**Comment by cuchakma** [comment]
@ixehad basically it shows the message because, wp_mail is a WordPress mail function. This function has a default behavior where it shows sent successfully because the function worked well without any errors regardless of the non-existent email address. If you somehow resend an email to a non-existent email address when in localhost(offline) not online, it will show failed because wp_mail generates an error message. Based on this error message the status of the emails are determined. This is a core function, and this behaviour cannot changed by default.

**Comment by ixehad** [comment]
example (other products)- https://prnt.sc/12y9w13

**Comment by cuchakma** [comment]
@ixehad recipient means that the email address is missing(empty), as I mentioned. If no email address is inserted it will show 'recipient is missing' it does not have any relation with a valid email address. Please note that the wp_mail function doesn't deal with existent or non-existent email addresses. it simply sends an email address from our end, it doesn't check whether the recipient has received the email or not. If we want such feature we have to build a custom function or use 3rdparty API's which are not free :) but expensive. But from our end it is not possible unless we use external functions
